### ISSUE TITLE
when I request GET api/v1/models/{tablename}/{recordId}/print

### ISSUE THREAD

**Issue by cooperong** [bxservice/idempiere-rest#154]
when I request GET api/v1/models/{tablename}/{recordId}/print, response "No serializer found for class com.trekglobal.idempiere.rest.api.util.ErrorBuilder and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)"

**Comment by d-ruiz** [comment]
Hi cooperong, thanks for creating the issue. 

I just changed the code so you get a proper response error in that case: https://github.com/bxservice/idempiere-rest/commit/f9215e84f7d1a272f4d7db4a98014af7b75baea3. 

The issue is probably that you're using a table that has no Print process associated, so the system cannot return any print output.
